# Generated by Django 5.2 on 2025-08-21 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0003_order_date_shipped'),
    ]

    operations = [
    ]
